"""post author

Revision ID: 01c08d9a7acc
Revises: 44c3760b211e
Create Date: 2018-12-05 04:57:12.720951

"""

# revision identifiers, used by Alembic.
revision = '01c08d9a7acc'
down_revision = '44c3760b211e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'blogs', ['author'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'author')
    # ### end Alembic commands ###
