"""unique tumblr id

Revision ID: 06583f4ea4d6
Revises: e200dce63f05
Create Date: 2018-12-05 06:21:18.914666

"""

# revision identifiers, used by Alembic.
revision = '06583f4ea4d6'
down_revision = 'e200dce63f05'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('blog_uid_unique', 'blogs', ['tumblr_uid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('blog_uid_unique', table_name='blogs')
    # ### end Alembic commands ###
