"""blog theme


Revision ID: 2518c83d2d63
Revises: e26f3256dd74
Create Date: 2018-12-12 23:09:57.723089

"""

# revision identifiers, used by Alembic.
revision = '2518c83d2d63'
down_revision = 'e26f3256dd74'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('theme', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'theme')
    # ### end Alembic commands ###
