"""blogs table

Revision ID: 44c3760b211e
Revises: f787bb5c68f6
Create Date: 2018-12-05 04:45:03.807400

"""

# revision identifiers, used by Alembic.
revision = '44c3760b211e'
down_revision = 'f787bb5c68f6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tumblr_uid', sa.String(), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('extra_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blogs')
    # ### end Alembic commands ###
