"""blog index on name

Revision ID: 5b6096b0b7b2
Revises: 7dc40a31e64e
Create Date: 2018-12-07 10:19:24.267565

"""

# revision identifiers, used by Alembic.
revision = '5b6096b0b7b2'
down_revision = '7dc40a31e64e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('index_blog_name', 'blogs', ['name'], unique=False)
    op.drop_index('index_post_url', table_name='posts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('index_post_url', 'posts', ['url'], unique=False)
    op.drop_index('index_blog_name', table_name='blogs')
    # ### end Alembic commands ###
