"""blog nsfw meta

Revision ID: 68aaa371e6e7
Revises: 06583f4ea4d6
Create Date: 2018-12-05 08:52:02.591153

"""

# revision identifiers, used by Alembic.
revision = '68aaa371e6e7'
down_revision = '06583f4ea4d6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('nsfw', sa.Boolean(), server_default='f', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'nsfw')
    # ### end Alembic commands ###
