"""author -> author_id

Revision ID: 7dc40a31e64e
Revises: 1e5f23d15ea3
Create Date: 2018-12-07 10:14:21.776000

"""

# revision identifiers, used by Alembic.
revision = '7dc40a31e64e'
down_revision = '1e5f23d15ea3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'author', new_column_name='author_id', existing_type=sa.Integer)
    op.drop_constraint('posts_author_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'blogs', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_author_fkey', 'posts', 'blogs', ['author'], ['id'])
    op.drop_column('posts', 'author_id')
    # ### end Alembic commands ###
