"""unique post id

Revision ID: 819f5ed728b0
Revises: 6aa1cdd2ad0b
Create Date: 2018-12-08 02:01:22.101846

"""

# revision identifiers, used by Alembic.
revision = '819f5ed728b0'
down_revision = '6aa1cdd2ad0b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('post_tumblr_id_unique', 'posts', ['tumblr_id', 'author_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('post_tumblr_id_unique', table_name='posts')
    # ### end Alembic commands ###
