"""last_crawl_update

Revision ID: 9dafd4fd2d5f
Revises: d00401ed8599
Create Date: 2018-12-08 03:25:42.357038

"""

# revision identifiers, used by Alembic.
revision = '9dafd4fd2d5f'
down_revision = 'd00401ed8599'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('last_crawl_update', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'last_crawl_update')
    # ### end Alembic commands ###
