"""blog name

Revision ID: a15171647482
Revises: 68aaa371e6e7
Create Date: 2018-12-05 08:59:24.345044

"""

# revision identifiers, used by Alembic.
revision = 'a15171647482'
down_revision = '68aaa371e6e7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'name')
    # ### end Alembic commands ###
