"""post body

Revision ID: bea0c896fc95
Revises: 2518c83d2d63
Create Date: 2018-12-13 09:18:40.475506

"""

# revision identifiers, used by Alembic.
revision = 'bea0c896fc95'
down_revision = '2518c83d2d63'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

from archives.lib.model import Post, sm

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('posts', sa.Column('body', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###

    # Force commit the operation
    conn = op.get_bind()
    conn.execute("COMMIT")

    updates = []
    added = 0
    db = sm()
    commit_db = sm()

    for post in db.query(Post).filter(sa.or_(
        Post.data.has_key("body"),
    )).yield_per(512):
        new_data = post.data.copy()
        update = {
            "id": post.id,
            "data": new_data
        }

        update["body"] = new_data.pop("body", post.body)

        updates.append(update)

        # Commit every 1024 posts.
        added += 1
        if len(updates) == 1024:
            commit_db.execute("SET synchronous_commit TO off")
            print(f"{added} posts processed.", flush=True)
            commit_db.bulk_update_mappings(Post, updates)
            commit_db.commit()
            updates.clear()

    if updates:
        commit_db.bulk_update_mappings(Post, updates)
        commit_db.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body')
    # ### end Alembic commands ###
