"""blog uid unique

Revision ID: e200dce63f05
Revises: 01c08d9a7acc
Create Date: 2018-12-05 04:59:45.989459

"""

# revision identifiers, used by Alembic.
revision = 'e200dce63f05'
down_revision = '01c08d9a7acc'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
