"""message index

Revision ID: f787bb5c68f6
Revises: 119072efec39
Create Date: 2015-12-28 19:38:29.744147

"""

# revision identifiers, used by Alembic.
revision = 'f787bb5c68f6'
down_revision = '119072efec39'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('index_post_url', 'posts', ['url'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('index_post_url', table_name='posts')
    ### end Alembic commands ###
