version: '2'
services:
  redis:
    image: redis:3.2.1-alpine
    restart: always

  web:
    build: .
    restart: always
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    env_file: .env

  celery:
    build: .
    restart: always
    command: "celery -A archives.tasks worker -P gevent --autoscale=4,1"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    env_file: .env
    
  flower:
    build: .
    restart: always
    command: "celery -A archives.tasks flower --port=5000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    env_file: .env