"""Initial commit

Revision ID: 119072efec39
Revises: 
Create Date: 2015-06-01 02:26:12.796222

"""

# revision identifiers, used by Alembic.
revision = '119072efec39'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
