---

- name: "Settings - Set swappiness to 0"
  sysctl:
    name: vm.swappiness
    value: 1
    state: present
    reload: true

- name: "Settings - Enable kernel IP forwarding for app server."
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    reload: true

- name: "Settings - Set map count to 262144"
  sysctl:
    name: vm.max_map_count
    value: 262144
    state: present
    reload: true

- name: "Settings - Set file descriptors limit to unlimited"
  lineinfile:
    path: "/etc/security/limits.d/000-ansible.conf"
    line: "{{ item }}"
    create: true
  with_items:
    - '* soft nofile unlimited'
    - '* hard nofile unlimited'

- name: "Settings - IPTables Save"
  shell: iptables-save > /etc/iptables.rules

- name: "Settings - Update global byobu statusrc"
  copy:
    src: byobu_status
    dest: /usr/share/byobu/status/status
    owner: root
    group: root
    mode: 0644

- name: "Settings - Set timezone to UTC"
  timezone:
    name: UTC

- name: "Settings - Setup rsyslog remote logging"
  lineinfile:
    path: "/etc/rsyslog.d/00-ansible.conf"
    line: "*.* @{{ syslog_server }}:{{ syslog_port }}"
    create: true
  register: rsyslog_config

- name: "Settings - Restart rsyslog daemon"
  systemd:
    name: rsyslog
    enabled: true
    state: restarted
  when: rsyslog_config.changed
