---

- name: "Packages - apt-get upgrade"
  apt:
    upgrade: yes
    cache_valid_time: 172800

- name: "Packages - Admin convienence packages"
  package:
    name:
      - byobu
      - htop
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - bridge-utils
      - fail2ban
    state: latest

- name: "Packages - GPG keys"
  apt_key:
    url: '{{ item.key }}'
    id: '{{ item.value }}'
    state: present
  with_dict:
      "https://download.docker.com/linux/ubuntu/gpg": "0EBFCD88"

- name: "Packages - App server repos"
  apt_repository:
    repo: '{{ item }}'
    state: present
  with_items:
    - 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable edge test'

- name: "Packages - App server support packages"
  package:
    name: '{{ item }}'
    state: latest
  with_items:
    - docker-ce
